//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cinnity.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyecto_Cinnity.RecursosLocalizables.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR Y CAMBIAR CONTRASEÑA.
        /// </summary>
        internal static string aceptarcambiar {
            get {
                return ResourceManager.GetString("aceptarcambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string agregarpel {
            get {
                return ResourceManager.GetString("agregarpel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir al carrito:.
        /// </summary>
        internal static string añcarrito {
            get {
                return ResourceManager.GetString("añcarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos: .
        /// </summary>
        internal static string apellidoscuenta {
            get {
                return ResourceManager.GetString("apellidoscuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AYUDA.
        /// </summary>
        internal static string ayuda {
            get {
                return ResourceManager.GetString("ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR ENTRADA.
        /// </summary>
        internal static string buscarentr {
            get {
                return ResourceManager.GetString("buscarentr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string cambContrasenya {
            get {
                return ResourceManager.GetString("cambContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR SESIÓN.
        /// </summary>
        internal static string cerrarsesion {
            get {
                return ResourceManager.GetString("cerrarsesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña:.
        /// </summary>
        internal static string confcontrasenyacuenta {
            get {
                return ResourceManager.GetString("confcontrasenyacuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Correo:.
        /// </summary>
        internal static string confcorreo {
            get {
                return ResourceManager.GetString("confcorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma tu nueva contraseña:.
        /// </summary>
        internal static string confirmaContra {
            get {
                return ResourceManager.GetString("confirmaContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu contraseña actual:.
        /// </summary>
        internal static string contraActual {
            get {
                return ResourceManager.GetString("contraActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRASEÑA: .
        /// </summary>
        internal static string contrasenya {
            get {
                return ResourceManager.GetString("contrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string contrasenyacuenta {
            get {
                return ResourceManager.GetString("contrasenyacuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORREO ELECTRÓNICO: .
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico:.
        /// </summary>
        internal static string correoelectronico {
            get {
                return ResourceManager.GetString("correoelectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREACIÓN DE CUENTA .
        /// </summary>
        internal static string creacioncuenta {
            get {
                return ResourceManager.GetString("creacioncuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR MI CUENTA.
        /// </summary>
        internal static string crearcuenta {
            get {
                return ResourceManager.GetString("crearcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR CUENTA.
        /// </summary>
        internal static string crearcuentanueva {
            get {
                return ResourceManager.GetString("crearcuentanueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es una aplicación para gestionar entradas de uno o varios cines 
        ///cuando escogas la película que más te guste. 
        ///
        ///También, a la hora de vender o comprar entradas, 
        ///obtendrás créditos CINNITY ´s para futuros descuentos o promociones..
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Director: .
        /// </summary>
        internal static string director {
            get {
                return ResourceManager.GetString("director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Director:.
        /// </summary>
        internal static string directorpel {
            get {
                return ResourceManager.GetString("directorpel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración: .
        /// </summary>
        internal static string duracion {
            get {
                return ResourceManager.GetString("duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración:.
        /// </summary>
        internal static string duracionpel {
            get {
                return ResourceManager.GetString("duracionpel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Información.
        /// </summary>
        internal static string editinfo {
            get {
                return ResourceManager.GetString("editinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string eliminarpel {
            get {
                return ResourceManager.GetString("eliminarpel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRADAS.
        /// </summary>
        internal static string entradas {
            get {
                return ResourceManager.GetString("entradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRADAS ACTIVAS.
        /// </summary>
        internal static string entradasact {
            get {
                return ResourceManager.GetString("entradasact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRADAS ADQUIRIDAS.
        /// </summary>
        internal static string entradasadquiridas {
            get {
                return ResourceManager.GetString("entradasadquiridas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de estreno:.
        /// </summary>
        internal static string fechaestreno {
            get {
                return ResourceManager.GetString("fechaestreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de estreno:.
        /// </summary>
        internal static string fechestrenopel {
            get {
                return ResourceManager.GetString("fechestrenopel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string filtrar {
            get {
                return ResourceManager.GetString("filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento:.
        /// </summary>
        internal static string fnac {
            get {
                return ResourceManager.GetString("fnac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género: .
        /// </summary>
        internal static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero:.
        /// </summary>
        internal static string generopel {
            get {
                return ResourceManager.GetString("generopel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a correo@gmail.com.
        /// </summary>
        internal static string gmail {
            get {
                return ResourceManager.GetString("gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Entrada:.
        /// </summary>
        internal static string identrada {
            get {
                return ResourceManager.GetString("identrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMACIÓN:.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR SESIÓN.
        /// </summary>
        internal static string iniciarSesión {
            get {
                return ResourceManager.GetString("iniciarSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Métodos de Pago.
        /// </summary>
        internal static string metpago {
            get {
                return ResourceManager.GetString("metpago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar contraseña.
        /// </summary>
        internal static string mostradContra {
            get {
                return ResourceManager.GetString("mostradContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string nombrecuenta {
            get {
                return ResourceManager.GetString("nombrecuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string nomusuario {
            get {
                return ResourceManager.GetString("nomusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu nueva contraseña:.
        /// </summary>
        internal static string nuevaContra {
            get {
                return ResourceManager.GetString("nuevaContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAGAR.
        /// </summary>
        internal static string pagar {
            get {
                return ResourceManager.GetString("pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País:.
        /// </summary>
        internal static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MI PERFIL.
        /// </summary>
        internal static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PREGUNTAS FRECUENTES:.
        /// </summary>
        internal static string preguntas {
            get {
                return ResourceManager.GetString("preguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera vez de acceso: 21 de Septiembre de 2010.
        /// </summary>
        internal static string primacceso {
            get {
                return ResourceManager.GetString("primacceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reparto:.
        /// </summary>
        internal static string reparto {
            get {
                return ResourceManager.GetString("reparto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reparto:.
        /// </summary>
        internal static string repartopel {
            get {
                return ResourceManager.GetString("repartopel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar imagen....
        /// </summary>
        internal static string seleccimagenpel {
            get {
                return ResourceManager.GetString("seleccimagenpel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar sesión.
        /// </summary>
        internal static string seleccsesion {
            get {
                return ResourceManager.GetString("seleccsesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SESIONES DISPONIBLES:.
        /// </summary>
        internal static string sesiones {
            get {
                return ResourceManager.GetString("sesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis:.
        /// </summary>
        internal static string sinopsis {
            get {
                return ResourceManager.GetString("sinopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis:.
        /// </summary>
        internal static string sinopsispel {
            get {
                return ResourceManager.GetString("sinopsispel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Entradas: .
        /// </summary>
        internal static string sumaentradas {
            get {
                return ResourceManager.GetString("sumaentradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título:.
        /// </summary>
        internal static string titulopel {
            get {
                return ResourceManager.GetString("titulopel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagina Principal.
        /// </summary>
        internal static string tituloventana {
            get {
                return ResourceManager.GetString("tituloventana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string tituloventana2 {
            get {
                return ResourceManager.GetString("tituloventana2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Perfil.
        /// </summary>
        internal static string tituloventana3 {
            get {
                return ResourceManager.GetString("tituloventana3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Entradas.
        /// </summary>
        internal static string tituloventana4 {
            get {
                return ResourceManager.GetString("tituloventana4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string tituloventana5 {
            get {
                return ResourceManager.GetString("tituloventana5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito de la Compra.
        /// </summary>
        internal static string tituloventana6 {
            get {
                return ResourceManager.GetString("tituloventana6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Entradas: 10.
        /// </summary>
        internal static string totalEntradas {
            get {
                return ResourceManager.GetString("totalEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Precio:.
        /// </summary>
        internal static string totalPrecio {
            get {
                return ResourceManager.GetString("totalPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última vez de acceso: 14 de marzo 2023.
        /// </summary>
        internal static string ultacceso {
            get {
                return ResourceManager.GetString("ultacceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VACIAR.
        /// </summary>
        internal static string vaciar {
            get {
                return ResourceManager.GetString("vaciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR ENTRADA.
        /// </summary>
        internal static string venderentr {
            get {
                return ResourceManager.GetString("venderentr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VOLVER.
        /// </summary>
        internal static string volver {
            get {
                return ResourceManager.GetString("volver", resourceCulture);
            }
        }
    }
}
